### ISSUE TITLE
Should handle invalid identifiers by adding backticks

### ISSUE THREAD

**Issue by mac9416** [cchandurkar/Case-Class-Generator-Issues#4]
If a property name contains a character which would invalidate the identifier, the case class should use a literal identifier by surrounding the name in backticks.

For example, a property with the name `some:name` should be represented in the case class as

```
  `some:name`: Type
```

**Comment by cchandurkar** [comment]
Yes, backticks are also needed for the reserved keywords like `class`, `type` etc.

**Comment by cchandurkar** [comment]
Update as of v1.1.1

Backticks are added for all the 39 reserved scala keywords: `abstract, case, catch, class, def, do, else, extends, false, final, finally, for, forSome, if, implicit, import, lazy, match, new, null, object, override, package, private, protected, return, sealed, super, this, throw, trait, try, true, type, val, var, while, with, yield` and also for parameter names with special character except underscore.
