### ISSUE TITLE
Is the source code hosted anywhere?

### ISSUE THREAD

**Issue by alexklibisz** [cchandurkar/Case-Class-Generator-Issues#5]
Hi -- very neat project. I'm wondering if the sourcecode is hosted anywhere? I think it would be neat to implement an SBT plugin that takes a Json Schema URL and generates scala case classes.

**Comment by niqdev** [comment]
Hello! Very interesting project indeed and i'm interested too in the source code or at least sharing the lib/approach/tech details. Thanks!

**Comment by cchandurkar** [comment]
Hi, the code is in the private repo as of now. I'm cleaning it up to make it more usable and extensible. Will make it public soon. I'm hoping to support more use cases than just converting JSON Schema to case classes. Probably support swagger specs in near future. Eventually integration with Open API (maybe).

**Comment by cchandurkar** [comment]
Hi, I have made the code open-source: [cchandurkar/json-schema-to-case-class](https://github.com/cchandurkar/json-schema-to-case-class). it is also published as [npm package](https://www.npmjs.com/package/json-schema-to-case-class) that works in both NodeJs and browser environment. 

The approach it takes is pretty simple:
 1. Validate schema.
 2. Resolve local/remote schema references.
 3. Recursively strip-down resolved JSON schema into a simplified format.
 4. Format simplified schema into a case class body text.

The intermediate simplified format will allow more types of schema conversions in the future (YAML).

**Comment by cchandurkar** [comment]
@alexklibisz I guess I should have mentioned this earlier but this is not built with Scala. It would be tricky to build an SBT plugin out of this. But it seems possible to use something like [sbt-js-engine](https://index.scala-lang.org/sbt/sbt-js-engine/sbt-js-engine/1.1.3?target=_2.10_0.13). 

It would be a lot easier to write a CLI on top of this library instead.
